"""
Pydantic schemas for Message API requests and responses.

Defines validation models for creating messages, adding reactions,
and streaming chat responses.
"""

from datetime import datetime
from typing import Optional, Literal
from pydantic import BaseModel, Field, ConfigDict


class MessageBase(BaseModel):
    """
    Base schema for Message with common fields.
    """
    role: Literal["user", "assistant"] = Field(
        ...,
        description="Message role (user or assistant)"
    )
    content: str = Field(
        ...,
        min_length=1,
        description="Message content"
    )


class MessageCreate(BaseModel):
    """
    Schema for creating a new message.

    Used internally by the chat endpoint.
    """
    conversation_id: int = Field(
        ...,
        gt=0,
        description="Conversation ID to add message to"
    )
    role: Literal["user", "assistant"] = Field(
        ...,
        description="Message role"
    )
    content: str = Field(
        ...,
        min_length=1,
        description="Message content"
    )
    parent_message_id: Optional[int] = Field(
        None,
        gt=0,
        description="Parent message ID (for regeneration)"
    )


class MessageResponse(MessageBase):
    """
    Schema for message API responses.

    Includes all database fields and metadata.
    """
    id: int = Field(..., description="Unique message ID")
    conversation_id: int = Field(..., description="Parent conversation ID")
    created_at: datetime = Field(..., description="Timestamp of creation")
    reaction: Optional[Literal["thumbs_up", "thumbs_down"]] = Field(
        None,
        description="User reaction to message"
    )
    parent_message_id: Optional[int] = Field(
        None,
        description="Parent message ID (for regeneration)"
    )
    token_count: int = Field(0, description="Number of tokens in message")
    model_name: Optional[str] = Field(None, description="LLM model used")
    completion_time_ms: Optional[int] = Field(
        None,
        description="Time taken to generate response (milliseconds)"
    )
    metadata: dict = Field(default_factory=dict, description="Additional metadata")

    # Pydantic v2 configuration
    model_config = ConfigDict(from_attributes=True)


class MessageListResponse(BaseModel):
    """
    Schema for paginated message list responses.
    """
    messages: list[MessageResponse] = Field(..., description="Array of messages")
    total_count: int = Field(
        ...,
        description="Total number of messages (for pagination)"
    )


class MessageReactionUpdate(BaseModel):
    """
    Schema for updating a message reaction.

    Allows setting or removing reactions (null removes reaction).
    """
    reaction: Optional[Literal["thumbs_up", "thumbs_down"]] = Field(
        None,
        description="Reaction type (null to remove reaction)"
    )


class ChatStreamRequest(BaseModel):
    """
    Schema for initiating a chat stream.

    Used by the SSE streaming endpoint.
    """
    conversation_id: int = Field(
        ...,
        gt=0,
        description="Conversation ID to add message to"
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="User message content (max 10,000 characters)"
    )


class SSETokenEvent(BaseModel):
    """
    Schema for SSE token events.

    Sent for each token generated by the LLM.
    """
    token: str = Field(..., description="Individual token from LLM")
    message_id: int = Field(..., description="Message ID being generated")
    session_id: str = Field(..., description="Session ID for cancellation")


class SSECompleteEvent(BaseModel):
    """
    Schema for SSE completion events.

    Sent when the LLM finishes generating a response.
    """
    message_id: int = Field(..., description="Completed message ID")
    token_count: int = Field(..., description="Total tokens generated")
    completion_time_ms: int = Field(
        ...,
        description="Time taken to generate response (milliseconds)"
    )


class SSEErrorEvent(BaseModel):
    """
    Schema for SSE error events.

    Sent when an error occurs during streaming.
    """
    error: str = Field(..., description="Error message")
    error_type: str = Field(
        ...,
        description="Error type (validation_error, service_error, etc.)"
    )
